name: task_wan_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  google_fonts: ^6.3.3
  flutter_svg: ^2.2.3
  flutter_gen: ^5.12.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
